spring:
  h2:
    console:
      enabled: true

  datasource:
    initialize: true
    url: jdbc:mariadb://capstone.cjbw8mzbnsxy.ap-northeast-2.rds.amazonaws.com:3306/tokentest
    driver-class-name: org.mariadb.jdbc.Driver
    username: capstone
    password: mjucapstone
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    me.silvernine: DEBUG


